version: "3.8"

services:

  app:
    build: .
    ports:
      - "8081:8081"
    networks:
      - app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mercX
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    volumes:
      - ./uploads:/app/uploads  # папка "uploads" в текущей директории
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mercX
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - pgadmin
      - app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./struct/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - pgadmin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin


  keycloak-db:
      image: postgres:15
      container_name: keycloak-db
      restart: always
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
      healthcheck:
        test: [ "CMD", "pg_isready", "-U", "keycloak" ]
        interval: 10s
        retries: 5
      networks:
        - pgadmin
        - app
      volumes:
        - keycloak-db-data:/var/lib/postgresql/data
      ports:
        - "5433:5432"  # Проброс порта 5432 с контейнера на хост



  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    restart: always
    depends_on:
      keycloak-db:
        condition: service_healthy
    ports:
      - "8085:8085"
    environment:
     # KC_HOSTNAME: mercx.auth.com
      KC_HTTP_ENABLED: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: [ "start-dev", "--http-port", "8085" ]
    volumes:
      - ./themes/my-custom-theme:/opt/keycloak/themes/my-custom-theme
    networks:
      - app


volumes:
  db-data:
  postgres_data:
  pgadmin-data:
  keycloak-db-data:

networks:
  pgadmin:
    name: db
    driver: bridge
  app:
    name: app-network
    driver: bridge