spring:
  application:
    name: mercX
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
#      username: postgres
#      password: root
#      url: jdbc:postgresql://db:5432/mercX
      driverClassName: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8085/realms/Freelance-Exchange
      client:
        registration:
          Freelance-Exchange:
            client-id: MercX
            client-secret: IZ0GK2jljulVPoYuGYwZsFCXLRE5CHLQ
            provider: Freelance-Exchange
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          Freelance-Exchange:
            #issuer-uri: http://172.19.0.2:8080/realms/mercx-realm  # для Spring Boot
            authorization-uri: http://localhost:8085/realms/Freelance-Exchange/protocol/openid-connect/auth
            token-uri: http://keycloak:8085/realms/Freelance-Exchange/protocol/openid-connect/token
            jwk-set-uri:  http://keycloak:8085/realms/Freelance-Exchange/protocol/openid-connect/certs
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


keycloak:
   server-url: http://keycloak:8085
   realm: Freelance-Exchange
   client-id: MercX
   client-secret: IZ0GK2jljulVPoYuGYwZsFCXLRE5CHLQ

server:
  port: 8081